# Generated by Django 4.1.5 on 2023-01-21 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dspm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='creado_por',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
