# Generated by Django 4.1.5 on 2023-01-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dspm', '0002_incidencia_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='agentes',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Agentes que detienen'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='autorizacion_salida',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Autorizacion de Salida'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='domicilio',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='edad',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado_civil',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='formato_pago',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Formato de Pago'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='lugar',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='pertenencias',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Pertenencias'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='salida',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='sexo',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Sexo'),
        ),
    ]
