#!/bin/bash

NAME="sac"
DIR=/home/sacgue/sac
USER=sacgue
GROUP=sacgue
WORKERS=3
BIND=unix:/home/sacgue/sac/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=sac.settings
DJANGO_WSGI_MODULE=sac.wsgi
LOG_LEVEL=error

cd $DIR

source /bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-

