# Generated by Django 3.2.8 on 2021-10-15 04:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='pendiente', max_length=40, unique=True, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(default='1234', max_length=100, verbose_name='Clave')),
                ('email', models.EmailField(default='1@2.com', max_length=100, unique=True, verbose_name='Correo Electronico ')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('imagen', models.ImageField(blank=True, default=None, max_length=200, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('usuario_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_administrador', models.BooleanField(default=False, verbose_name='Administrador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True, verbose_name='Nombre Departamento')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('categoria', models.CharField(default='pendiente', max_length=25, verbose_name='Categoria')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('telefono', models.CharField(max_length=25, verbose_name='Telefono')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('rubro', models.CharField(max_length=25, verbose_name='Rubro')),
                ('direccion', models.TextField(max_length=355, verbose_name='Direccion')),
                ('rfc', models.CharField(max_length=30, verbose_name='RFC')),
                ('contacto', models.CharField(max_length=50, verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=50, verbose_name='Concepto')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion')),
                ('estatus', models.CharField(default='pendiente', max_length=15, verbose_name='Estatus')),
                ('fecha_estatus', models.DateField(auto_now=True, verbose_name='Fecha de Estatus ')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.departamento')),
                ('persona_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisicion',
                'verbose_name_plural': 'Requisiciones',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.SmallIntegerField()),
                ('persona_id', models.CharField(max_length=30, verbose_name='Persona')),
                ('concepto', models.CharField(max_length=15, verbose_name='Concepto')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion')),
                ('estatus', models.CharField(default='revisado', max_length=15, verbose_name='Estatus')),
                ('fecha_estatus', models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 19, 44, 885336), verbose_name='Fecha Estatus')),
                ('aprobador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.departamento')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.proveedor')),
                ('recursos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.recurso')),
            ],
            options={
                'verbose_name': 'OrdenCompra',
                'verbose_name_plural': 'OrdenesCompras',
                'ordering': ['Folio'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=25, verbose_name='Categoria')),
                ('unidad_medida', models.CharField(max_length=15, verbose_name='Unidad de Medida')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion')),
                ('stock', models.CharField(max_length=15, verbose_name='Stock')),
                ('stock_min', models.CharField(max_length=15, verbose_name='Stock Minimo')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.SmallIntegerField()),
                ('persona_id', models.CharField(max_length=30, verbose_name='Persona')),
                ('concepto', models.CharField(max_length=15, verbose_name='Concepto')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion')),
                ('pdf', models.FileField(upload_to='uploads/', verbose_name='PDF')),
                ('xml', models.FileField(upload_to='uploads/', verbose_name='XML')),
                ('estatus', models.CharField(default='Comprado', max_length=15, verbose_name='Estatus')),
                ('fecha_estatus', models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 19, 44, 886335), verbose_name='Fecha Estatus')),
                ('aprobador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.departamento')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.proveedor')),
                ('recursos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.recurso')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['Folio'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=20, verbose_name='Id')),
                ('estatus', models.CharField(max_length=20, verbose_name='Estatus')),
                ('persona_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.departamento'),
        ),
    ]
