# Generated by Django 3.2.8 on 2021-10-15 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20211014_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administrador',
            new_name='is_staff',
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 11, 48, 7, 266790), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 11, 48, 7, 262431), verbose_name='Fecha Estatus'),
        ),
    ]
