# Generated by Django 3.2.8 on 2021-10-18 01:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20211015_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 19, 35, 7, 27534), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 19, 35, 7, 24535), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='persona_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.departamento'),
        ),
    ]
