# Generated by Django 3.2.8 on 2021-10-18 01:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20211017_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['id'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['id'], 'verbose_name': 'OrdenCompra', 'verbose_name_plural': 'OrdenesCompras'},
        ),
        migrations.AlterModelOptions(
            name='requisicion',
            options={'ordering': ['id'], 'verbose_name': 'Requisicion', 'verbose_name_plural': 'Requisiciones'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='Folio',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='Folio',
        ),
        migrations.AddField(
            model_name='compra',
            name='ordenCompra_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='personas.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='requerimiento_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='personas.requisicion'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='persona_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compra',
            name='aprobador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compra',
            name='departamento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.departamento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 19, 48, 40, 859550), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='recursos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.recurso'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.producto'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='aprobador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='departamento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.departamento'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 19, 48, 40, 858550), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.proveedor'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='recursos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.recurso'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='departamento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.departamento'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='persona_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
