# Generated by Django 3.2.8 on 2021-10-18 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20211017_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='producto_id',
            field=models.ManyToManyField(default=None, to='personas.Producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 14, 13, 45, 816077), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 14, 13, 45, 815077), verbose_name='Fecha Estatus'),
        ),
    ]
