# Generated by Django 3.2.8 on 2021-10-18 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20211018_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 16, 5, 33, 433824), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 16, 5, 33, 432825), verbose_name='Fecha Estatus'),
        ),
    ]
