# Generated by Django 3.2.8 on 2021-10-18 23:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_auto_20211018_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 17, 3, 55, 432840), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_estatus',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 17, 3, 55, 431839), verbose_name='Fecha Estatus'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='persona_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='producto_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='personas.producto'),
        ),
    ]
