# Generated by Django 3.2.8 on 2021-10-21 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_auto_20211018_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='departamento_id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='persona_id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedor_id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='recursos_id',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='departamento_id',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='persona_id',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='tipo_documento',
            field=models.CharField(default=None, max_length=60, verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='producto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='personas.producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_estatus',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Estatus '),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='descripcion',
            field=models.TextField(max_length=250, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_estatus',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Estatus '),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='', max_length=25, verbose_name='Categoria'),
        ),
    ]
