# Generated by Django 3.2.8 on 2021-10-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_auto_20211020_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='impresa',
            field=models.CharField(default=0, max_length=5, verbose_name='Veces Impresa'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.producto'),
        ),
    ]
