# Generated by Django 3.2.8 on 2021-10-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_auto_20211021_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='cantidad_prod',
            field=models.CharField(default=0, max_length=20, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='precio_total',
            field=models.CharField(default=0, max_length=60, verbose_name='Precio Total'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='precio_unitario',
            field=models.CharField(default=0, max_length=60, verbose_name='Precio Unitario'),
        ),
    ]
