# Generated by Django 3.2.8 on 2021-10-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0011_auto_20211021_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='cantidad_prod',
            field=models.CharField(default=1, max_length=20, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_estatus',
            field=models.DateField(verbose_name='Fecha de Estatus '),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_estatus',
            field=models.DateField(verbose_name='Fecha de Estatus '),
        ),
    ]
