# Generated by Django 3.2.8 on 2021-10-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_auto_20211021_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='Total',
            field=models.CharField(default=None, max_length=20, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='compra',
            name='descripcion',
            field=models.TextField(default=None, max_length=300, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_estatus',
            field=models.DateField(verbose_name='Fecha de Estatus '),
        ),
    ]
