# Generated by Django 3.2.8 on 2021-11-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0017_auto_20211103_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='estatus',
            field=models.CharField(max_length=60, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='folio',
            field=models.CharField(max_length=60, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tipo_documento',
            field=models.CharField(default=None, max_length=70, verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.CharField(default=None, max_length=60, verbose_name='Nombre'),
        ),
    ]
