# Generated by Django 4.1.5 on 2023-01-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0018_auto_20211103_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=45, verbose_name='Nombre del Concepto')),
                ('clave', models.CharField(default=None, max_length=50, verbose_name='Clave')),
                ('precio', models.CharField(default=0, max_length=20, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(default=None, max_length=20, verbose_name='Cantidad')),
                ('precio_unitario', models.CharField(default=None, max_length=20, verbose_name='Precio Unitario')),
                ('subtotal', models.CharField(default=None, max_length=20, verbose_name='Sub total')),
                ('concepto_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.concepto')),
            ],
        ),
        migrations.CreateModel(
            name='TiposVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=60, verbose_name='Nombre')),
                ('descripcion', models.CharField(default=None, max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'TiposVehiculo',
                'verbose_name_plural': 'TiposVehiculos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='rubro',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='concepto',
        ),
        migrations.AddField(
            model_name='producto',
            name='en_uso',
            field=models.CharField(default='no', max_length=2, verbose_name='En Uso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='visible',
            field=models.CharField(default='si', max_length=100, verbose_name='visible'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='listar',
            field=models.CharField(default='si', max_length=15, verbose_name='Listar'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='proveedor_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.proveedor'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='recursos_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.recurso'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='folio',
            field=models.CharField(max_length=160, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='producto_id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True, verbose_name='Correo Electronico '),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente')),
                ('monto', models.CharField(max_length=45, null=True, verbose_name='Monto')),
                ('visible', models.CharField(default='si', max_length=100, verbose_name='visible')),
                ('concepto_id', models.ManyToManyField(blank=True, default=None, through='personas.ConceptoVenta', to='personas.concepto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha de Creacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('num_economico', models.CharField(default='', max_length=70, verbose_name='Numero Económico')),
                ('marca', models.CharField(max_length=100, null=True, verbose_name='Marca')),
                ('submarca', models.CharField(default='', max_length=100, null=True, verbose_name='Submarca')),
                ('modelo', models.CharField(max_length=100, null=True, verbose_name='Modelo')),
                ('placas', models.CharField(default='', max_length=50, null=True, verbose_name='Placas')),
                ('color', models.CharField(default='', max_length=50, null=True, verbose_name='Color')),
                ('visible', models.CharField(default='si', max_length=3, verbose_name='visible')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha de Ultimo Servicio')),
                ('anotaciones', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='Anotaciones')),
                ('departamento_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.departamento')),
                ('tipo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.tiposvehiculo')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='conceptoventa',
            name='venta_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.venta'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='vehiculo_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.vehiculo'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='producto_id',
            field=models.ManyToManyField(default=None, to='personas.producto'),
        ),
    ]
